import Cocoa
import SpriteKit

// Export authored geometry and artwork; browser runtime has no Swift dependency.
func exportWeb(to path:String) throws {
    func p(_ v:CGPoint)->[CGFloat] {[v.x,v.y]}
    func r(_ v:CGRect)->[CGFloat] {[v.minX,v.minY,v.width,v.height]}
    func rgba(_ c:NSColor,_ alpha:CGFloat)->String {
        let c=c.usingColorSpace(.deviceRGB)!
        return String(format:"rgba(%d,%d,%d,%.3f)",Int(c.redComponent*255),Int(c.greenComponent*255),Int(c.blueComponent*255),Double(c.alphaComponent*alpha))
    }
    func art(_ root:SKNode,excluding:Set<ObjectIdentifier>=[])->[[Any]] {
        var result=[[Any]]()
        func visit(_ n:SKNode,_ x:CGFloat,_ y:CGFloat,_ sx:CGFloat,_ sy:CGFloat,_ angle:CGFloat,_ opacity:CGFloat) {
            if n.isHidden || excluding.contains(ObjectIdentifier(n)) {return}
            let dx=n.position.x*sx,dy=n.position.y*sy
            let x=x+cos(angle)*dx-sin(angle)*dy,y=y+sin(angle)*dx+cos(angle)*dy
            let sx=sx*n.xScale,sy=sy*n.yScale,a=angle+n.zRotation,opacity=opacity*n.alpha
            if let s=n as? SKSpriteNode {
                result.append(["r",x,y,s.size.width*sx,s.size.height*sy,rgba(s.color,opacity),a])
            } else if let l=n as? SKLabelNode,let text=l.text {
                result.append(["t",x,y,text,l.fontSize,rgba(l.fontColor ?? .white,opacity),l.horizontalAlignmentMode == .left ? "left":l.horizontalAlignmentMode == .right ? "right":"center"])
            }
            for (_,child) in n.children.enumerated().sorted(by:{$0.element.zPosition == $1.element.zPosition ? $0.offset<$1.offset:$0.element.zPosition<$1.element.zPosition}) {visit(child,x,y,sx,sy,a,opacity)}
        }
        visit(root,0,0,1,1,0,1);return result
    }
    let g=Game(size:CGSize(width:W,height:H));var levels=[[String:Any]]()
    for index in missions.indices {
        g.levelIndex=index;g.reset()
        var excluded:Set<ObjectIdentifier>=[ObjectIdentifier(g.player),ObjectIdentifier(g.gate)]
        for n in g.enemies.map({$0.node})+g.pickups.map({$0.node})+g.supplies.map({$0.node}) {excluded.insert(ObjectIdentifier(n))}
        // Camera parallax is applied at runtime, so export unshifted layers.
        g.sky.position = .zero;g.backdrop.position = .zero
        levels.append(["name":g.mission.name,"subtitle":g.mission.subtitle,"width":g.mission.width,"height":g.mission.height,
            "accent":String(format:"#%06x",g.mission.accent),"spawn":p(g.mission.spawn),"exit":p(g.mission.exit),
            "platforms":g.platforms.map{r($0.r)},"enemies":g.enemies.map{["x":$0.x,"y":$0.y,"boss":$0.boss] as [String:Any]},
            "pickups":g.pickups.map{["x":$0.node.position.x,"y":$0.node.position.y,"kind":$0.kind] as [String:Any]},
            "supplies":g.supplies.map{p($0.node.position)},"warps":g.mission.warps.map{["name":$0.name,"a":p($0.a),"b":p($0.b)] as [String:Any]},
            "sky":art(g.sky),"backdrop":art(g.backdrop),"scenery":art(g.world,excluding:excluded)])
    }
    let data:[String:Any]=["levels":levels,"sprites":["hero":art(heroArt()),"drone":art(droneArt()),"boss":art(bossArt()),"cell":art(cellArt()),"medkit":art(medkitArt()),"supply":art(supplyArt()),"weapon":art(weaponArt())]]
    let json=try JSONSerialization.data(withJSONObject:data,options:[.sortedKeys])
    try ("// Generated by ./play.command --export-web docs/data.mjs\nexport default "+String(data:json,encoding:.utf8)!+";\n").write(toFile:path,atomically:true,encoding:.utf8)
    print("Exported \(levels.count) missions and pixel artwork to \(path)")
}
